name: AzuriaDailyRewards
version: 1.0
api-version: 1.20
main: fr.azuriapvp.dailyrewards.AzuriaDailyRewards
commands:
  dailyrewards:
    description: Ouvre le menu des récompenses quotidiennes.
    usage: /dailyreward
